### ISSUE TITLE
Wrong stripe color of elements inside folder with custom theme.

### ISSUE THREAD

**Issue by rvega** [braitsch/ofxDatGui#36] opened 2016-01-17 09:56 UTC
I created  a custom theme that only changes width and font size: 

```
class AppGuiTheme: public ofxDatGuiTheme{
  public:
    AppGuiTheme(){
      font.size = 8;
      layout.width = 300;
      init();
    }
};
```

Then I created a gui, applied the theme (gui->setTheme(new AppGuiTheme())), added two folders (gui->addFolder()) and some elements within the folders (f1->addButton()).

The elements within the folders end up with the default theme stripe color instead of the color for the folder. The expected behavior is that the elements have the folder's color.

If I remove the gui->setTheme() statement, the default theme is used and the elements within the folders correctly render with the folder's color.

**Comment by braitsch** [comment] 2016-01-17 18:27
Apply the theme after adding all the components to the folder. Individual components (folders, buttons, etc) do not store a reference to any applied themes like a gui does. This may change in the future but for now you'll have to apply the theme after constructing the folder.

**Comment by rvega** [comment] 2016-01-17 20:50
Thanks for the reply :)

It still does not work after doing that. Here's my code and a screenshot of the rendered GUI.

```
  ofxDatGui* gui = new ofxDatGui(ofxDatGuiAnchor::TOP_LEFT);

  ofColor yellow = ofColor::fromHex(0xFFD00B);
  ofxDatGuiFolder* f1 = gui->addFolder("DSP PARAMETERS", yellow);
  f1->addSlider("  Slider", 0, 1);
  f1->addButton("  Button");
  f1->addBreak();
  f1->expand();

  ofColor green = ofColor::fromHex(0x1ED36F);
  ofxDatGuiFolder* f2 = gui->addFolder("TEXT OUTPUT", green);
  f2->addButton("  Copy");
  f2->addButton("  Clear");
  f2->expand();

  gui->setTheme(new AppGuiTheme());

  f1->onButtonEvent(this, &GUI::clickedButton);
  f1->onSliderEvent(this, &GUI::changedSlider);
  f2->onButtonEvent(this, &GUI::clickedButton);
  f2->onSliderEvent(this, &GUI::changedSlider);
```

![screenshot-2016-01-17-21 47 47](https://cloud.githubusercontent.com/assets/37172/12379875/037edbc6-bd64-11e5-93e7-153f54b970dc.png)

**Comment by braitsch** [comment] 2016-01-22 22:57
Hi, I just copied and pasted your code into a new project, applied one of the stock themes and this is what I'm seeing.

```
ofxDatGui* gui = new ofxDatGui(ofxDatGuiAnchor::TOP_LEFT);

ofColor yellow = ofColor::fromHex(0xFFD00B);
ofxDatGuiFolder* f1 = gui->addFolder("DSP PARAMETERS", yellow);
f1->addSlider("  Slider", 0, 1);
f1->addButton("  Button");
f1->addBreak();
f1->expand();

ofColor green = ofColor::fromHex(0x1ED36F);
ofxDatGuiFolder* f2 = gui->addFolder("TEXT OUTPUT", green);
f2->addButton("  Copy");
f2->addButton("  Clear");
f2->expand();

gui->setTheme(new ofxDatGuiThemeCharcoal());

f1->onButtonEvent(this, &ofApp::clickedButton);
f1->onSliderEvent(this, &ofApp::changedSlider);
f2->onButtonEvent(this, &ofApp::clickedButton);
f2->onSliderEvent(this, &ofApp::changedSlider);
```

<img width="282" alt="screen shot 2016-01-22 at 2 56 27 pm" src="https://cloud.githubusercontent.com/assets/144289/12525336/5a4bf2a6-c118-11e5-9ae7-40fa5aa9b8f2.png">

Are you using the latest on master?

**Comment by braitsch** [comment] 2016-01-23 21:28
Closing as I'm not able to reproduce the issue. Feel free to reopen if you can provide more information.

**Comment by rvega** [comment] 2016-01-24 16:46
May I ask which theme you applied? I saw that all of them, except the default one hide the stripe, so the issue would not be visible. Also, note that I'm applying a custom theme.

Maybe this is a feature, not a bug. Let's see: When you are using the default theme, are the elements within a folder supposed to "inherit" the stripe color from the folder? If so, then this is a bug. If not, it's expected behavior.

To reproduce, create and apply a custom theme by inheriting and overriding some properties from the default theme (not the stripe color). The posted example is exactly what I'm describing.

**Comment by braitsch** [comment] 2016-01-26 01:17
Hi, sorry this is a bug. I didn't at first realize what you were describing but I see what you mean now. I just pushed up a patch that should resolve this. 64d7f7994dbe049efa3d2bab4b47c7f860eda80b

**Closed** 2016-01-28 15:43 UTC
Labels: bug
