### ISSUE TITLE
ofxDatGuiDropdown not collapsing after select when added to ofxDatGui

### ISSUE THREAD

**Issue by mrbichel** [braitsch/ofxDatGui#46] opened 2016-03-02 10:29 UTC
ofxDatGuiDropdown works fine by itself rendered as a component, collapsing after you select an option. But if you add it to an ofxDatGui it does not collapse after select. 

<img width="322" alt="screenshot 2016-03-02 11 27 28" src="https://cloud.githubusercontent.com/assets/38772/13457809/5510a0ea-e06a-11e5-99e2-bb67c6ee6ef3.png">

<img width="333" alt="screenshot 2016-03-02 11 27 41" src="https://cloud.githubusercontent.com/assets/38772/13457810/55161aa2-e06a-11e5-9db6-4b433984ff89.png">

**Comment by braitsch** [comment] 2016-03-02 14:58
Sure it does, take a look at the "allComponentsGui" example. How exactly are you adding it to you gui?

**Comment by mrbichel** [comment] 2016-03-02 15:25
Adapted your dropdown example to reproduce.

ofApp.h
ofxDatGui * gui; 

ofApp.cpp setup
    gui = new ofxDatGui(100,100);

// create a vector of colors to populate our dropdown //
    colors.push_back(ofColor::fromHex(0xFFD00B));
    colors.push_back(ofColor::fromHex(0x2FA1D6));
    colors.push_back(ofColor::fromHex(0x1ED36F));
    colors.push_back(ofColor::fromHex(0xC63256));
    
// convert the hex values of those colors to strings for the menu labels //
    vector<string> options;
    for (int i=0; i<colors.size(); i++) options.push_back(getHex(colors[i].getHex()));

// instantiate the dropdown //
    //menu = new ofxDatGuiDropdown("SELECT A COLOR", options);
    menu = gui->addDropdown("SELECT A COLOR", options);
    
    // not collapsing when added to gui


ofApp.cpp draw
    gui->draw();

**Comment by braitsch** [comment] 2016-03-04 05:48
Ok, I'm on holiday at the moment. Will look at this when I get back.

**Comment by mrbichel** [comment] 2016-03-15 15:00
We added a fix in our fork here: https://github.com/mrbichel/ofxDatGui/commit/0255fc9edf53cab785bcc3968cf13f3bc0060e93.
Also added an event that you can listen to for folder collapses.

**Comment by braitsch** [comment] 2016-03-18 23:04
I'm having difficulty reproducing the behavior you're seeing. Here's the exact code I'm using.

ofApp.h

````
#include "ofMain.h"
#include "ofxDatGui.h"

class ofApp : public ofBaseApp{
    public:
        void setup();
        void update();
        void draw();
        ofxDatGui * gui;
        ofxDatGuiDropdown * menu;
        vector<ofColor> colors;
};

````
ofApp.cpp

````
void ofApp::setup()
{
    gui = new ofxDatGui(100,100);

// create a vector of colors to populate our dropdown //
    colors.push_back(ofColor::fromHex(0xFFD00B));
    colors.push_back(ofColor::fromHex(0x2FA1D6));
    colors.push_back(ofColor::fromHex(0x1ED36F));
    colors.push_back(ofColor::fromHex(0xC63256));

// convert the hex values of those colors to strings for the menu labels //
    vector<string> options;
    for (int i=0; i<colors.size(); i++) options.push_back(ofToString(colors[i]));

// instantiate the dropdown //
    menu = gui->addDropdown("SELECT A COLOR", options);
}
````
I don't believe anything has changed recently that would affect how the gui or dropdown is rendered, regardless of this though are you using the latest on master?

**Comment by braitsch** [comment] 2016-03-22 18:27
Closing as unable to reproduce.

**Closed by braitsch** 2016-03-22 18:27 UTC

**Comment by oneandonlyoddo** [comment] 2016-08-23 15:29
Hello,
I am experiencing the same problem. For me it only happens if I add an event callback like so: 

`presetSelect->onDropdownEvent(this, &ofApp::onDropdownEvent);`

Even if the callback is empty. Removing the callback makes the Dropdown work again as expected but yeah then I don't have a callback :D

I looked through the code and if I get it right the necessary steps for correctly collapsing the dropdown are:

1. collapse()
2. layout();
3. layoutGui();

And here is where it happens. So far I wasn't able to figure out why but with an event callback added layoutGui() doesn't get called and ergo the expanded gui doesn't collapse.

**Comment by josh-byster** [comment] 2018-04-21 07:34
I'm experiencing the same issue - I have the latest version from master and the exact same issue is happening to me with the dropdown toggling. @braitsch also thank you for making this awesome addon!
