### ISSUE TITLE
my ofxDatGUI is visible on one macbook pro and not on another

### ISSUE THREAD

**Issue by batchku** [braitsch/ofxDatGui#120] opened 2017-02-12 16:44 UTC
I have a strange issue where my openframeworks app's GUI, made with the latest ofxDatGui, is visible and functional on one macbook pro (a "MacBook Pro (Retina, 15-inch, Early 2013)"), and not vislble on another one (a MacBook Pro (Retina, 15-inch, Late 2013).  The former is running El Capitain, and the latter Sierra.  On the laptop that isn't able to show the GUI, i see no text in my gui buttons/sliders.  They do however continue to "work", i.e. clickong on them does things.

Anyone seen this before?

-ali

**Comment by braitsch** [comment] 2017-02-13 04:31
Not able to show the text in the gui or not able to show the gui at all? A common mistake is to not link the font file correctly which renders the text as solid rectangles. Can you post a screenshot? Also are you using the same version of OF on both machines?

**Comment by batchku** [comment] 2017-02-13 15:41
Hello @braitsch ! Thank you for your response.

Both computers are running a built-application (not compiling in xcode).  They are running the same application; i tried building the app with of 0.9.3 and also with 0.9.8.  

Here is the screenshot  on one laptop:
![screenshot 2017-02-13 10 39 07](https://cloud.githubusercontent.com/assets/518356/22889962/da060d32-f1d8-11e6-93ab-63844b65aa43.png)

Here it is on the other laptop:
![screen shot 2017-02-12 at 17 08 42](https://cloud.githubusercontent.com/assets/518356/22889981/e75bcef4-f1d8-11e6-90fe-ff12cbc9d415.png)

How can I make sure not to make the common missing font mistake when using standalone apps?  
If you have any other advice also, i'd be grateful.

Regards,

Ali

**Comment by kritzikratzi** [comment] 2017-02-13 15:52
it looks like it's missing the font. 

usually this will be one of two things: 
1. you forgot to copy the font along
2. you're running into gatekeeper issues

(1) to test this you can run `sudo opensnoop | grep myAppName` to see the full paths the application is trying to read/write. (run that command before starting the application!). opensnoop will tell you if the file was openend/not found/etc. 
(2) to test this, you can start the app from the terminal (this will run your app without gatekeeper). something like `./myOfApp.app/Contents/MacOS/myOfApp`. if it works fine when run from terminal, but not when you double click, then you have a gatekeeper problem. 

either way, imho this is not related to ofxDatGui.

**Comment by braitsch** [comment] 2017-02-14 03:13
It does look like it's not seeing the [ofxbraitsch](https://github.com/braitsch/ofxDatGui/tree/master/ofxbraitsch) assets folder which contains the fonts and icons used by the addon. If you right click on the app and select **show package contents** you should see this directory at ``Contents -> Resources -> data -> ofxbraitsch``. If that directory does not exist inside of your compiled app try setting the ofDataPathRoot within your ofApp.cpp file and copying the ofxbraitsch folder into your app via a build phase script.

Inside ofApp.cpp:
``ofSetDataPathRoot("../Resources/data");``

Then select the **build phases** tab in your Xcode project and add the following line in the **run scripts** window:
``cp -r bin/data "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/Resources";``

**Comment by braitsch** [comment] 2018-06-10 04:43
Closing as not reproducible and likely not related to ofxDatGui.

**Closed by braitsch** 2018-06-10 04:43 UTC
